In [2]:
from array import *

1.  Create an array and traverse it.

In [3]:
arr = array('i',[12,122,33,45,25,63,11,6,2,22])

In [4]:
for i in arr:
    print(i)

# Note: Space Complexity for creating arr is O(n) and Time Complexity for traversing arr is O(n) as well.

12
122
33
45
25
63
11
6
2
22


2. Access individual elements through indexes

In [5]:
arr[0]

12

In [6]:
arr[-1]

22

In [7]:
arr[3:6]

array('i', [45, 25, 63])

In [8]:
arr[::-1]

# Note: Time and Space complexity for accessing any individual element from an array is O(1)

array('i', [22, 2, 6, 11, 63, 25, 45, 33, 122, 12])

3. Append any value to the array using the append() method

In [9]:
arr.append(100)

# Note: Appending a value at the end of an array has a Time and Space complexity of O(1)

In [10]:
arr

array('i', [12, 122, 33, 45, 25, 63, 11, 6, 2, 22, 100])

4. Insert value in an array using the insert() method

In [11]:
arr.insert(9,200)

In [12]:
arr

# Note: Inserting anywhere within the array has a Time Complexity of O(n) and Space Complexity of O(1)

array('i', [12, 122, 33, 45, 25, 63, 11, 6, 2, 200, 22, 100])

5. Extend an array using the extend method

In [13]:
arr2 = array('i',[1,2,3,4,5])

In [14]:
arr.extend(arr2)

In [15]:
arr

# Note: Extending the array has a Time and Space Complexity of O(n)

array('i', [12, 122, 33, 45, 25, 63, 11, 6, 2, 200, 22, 100, 1, 2, 3, 4, 5])

6. Add items from list into array using fromlist() method

In [16]:
my_list=[20,30,40,50]

In [17]:
arr.fromlist(my_list)

In [18]:
arr

array('i', [12, 122, 33, 45, 25, 63, 11, 6, 2, 200, 22, 100, 1, 2, 3, 4, 5, 20, 30, 40, 50])

7. Remove any array element using remove() method

In [19]:
arr.remove(12)

In [20]:
arr
# Note: Removing an element from the array has a Time Complexity of O(n) and a Space Complexity of O(1)

array('i', [122, 33, 45, 25, 63, 11, 6, 2, 200, 22, 100, 1, 2, 3, 4, 5, 20, 30, 40, 50])

8. Remove the last element of an array using the pop() method

In [21]:
print(arr)
arr.pop()
print(arr)

array('i', [122, 33, 45, 25, 63, 11, 6, 2, 200, 22, 100, 1, 2, 3, 4, 5, 20, 30, 40, 50])
array('i', [122, 33, 45, 25, 63, 11, 6, 2, 200, 22, 100, 1, 2, 3, 4, 5, 20, 30, 40])


9. Fetch any element through it's index using the index() method

In [22]:
arr.index(33)

1

10. Reverse an array using the reverse() method

In [23]:
arr.reverse()
print(arr)

array('i', [40, 30, 20, 5, 4, 3, 2, 1, 100, 22, 200, 2, 6, 11, 63, 25, 45, 33, 122])


11. Get array buffer information through buffer_info() method

In [24]:
arr.buffer_info()

(1444261716272, 19)

12. Check for number of occurences of an element using count() method

In [25]:
arr.count(2)

2

13. Convert array to list using tolist() method

In [26]:
print(arr.tolist())
print(arr)

[40, 30, 20, 5, 4, 3, 2, 1, 100, 22, 200, 2, 6, 11, 63, 25, 45, 33, 122]
array('i', [40, 30, 20, 5, 4, 3, 2, 1, 100, 22, 200, 2, 6, 11, 63, 25, 45, 33, 122])


15. Slice elements from an array

In [27]:
arr[3:10]

array('i', [5, 4, 3, 2, 1, 100, 22])

---

2D Arrays

In [28]:
import numpy as np

In [29]:
arr2 = np.array([[13,22,75,36],[22,74,90,10],[11,19,66,71]])

# Note: The time and space complexity for creating a 2d-array is O(mXn) where m = no. of rows and n=no. of columns

In [30]:
arr2

array([[13, 22, 75, 36],
       [22, 74, 90, 10],
       [11, 19, 66, 71]])

---

Insertion in 2d arrays:
1. Adding columns: Each column moves 1 step forward (time consuming - O(m X n))
2. Adding rows =: Each row moves 1 step down (time consuming - O(m X n))

In [31]:
arr2

array([[13, 22, 75, 36],
       [22, 74, 90, 10],
       [11, 19, 66, 71]])

In [32]:
# using the insert() method to add a column
np.insert(arr2,0,[[0,0,0]],axis=1)

array([[ 0, 13, 22, 75, 36],
       [ 0, 22, 74, 90, 10],
       [ 0, 11, 19, 66, 71]])

In [33]:
# using the insert() method to add a row
np.insert(arr2,0,[[0,0,0,0]],axis=0)

array([[ 0,  0,  0,  0],
       [13, 22, 75, 36],
       [22, 74, 90, 10],
       [11, 19, 66, 71]])

In [34]:
# using the append method to add row
np.append(arr2,[[0,0,0,0]],axis=0)

array([[13, 22, 75, 36],
       [22, 74, 90, 10],
       [11, 19, 66, 71],
       [ 0,  0,  0,  0]])

In [35]:
# using the append method to add column
np.append(arr2,[[0],[0],[0]],axis=1)

array([[13, 22, 75, 36,  0],
       [22, 74, 90, 10,  0],
       [11, 19, 66, 71,  0]])

In [36]:
# make numpy automatically detect dimentions and append a given row
arr_to_append = np.array([[0,0,0]])

In [37]:
arr_to_append = arr_to_append.reshape(arr2.shape[0], -1)

In [38]:
np.append(arr2,arr_to_append,axis=1)

array([[13, 22, 75, 36,  0],
       [22, 74, 90, 10,  0],
       [11, 19, 66, 71,  0]])

In [39]:
# Example: Assuming this is your twoDArray
twoDArray = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(twoDArray)
# The new array to append
new_array = np.array([21, 31, 41, 51])
print(new_array)
# Reshape new_array to have the same number of rows as twoDArray and 1 column
new_array = new_array.reshape(twoDArray.shape[0], -1)
print(new_array)
# Append new_array to twoDArray
new_append = np.append(twoDArray, new_array, axis=1)
print(new_append)

[[1 2 3 4]
 [5 6 7 8]]
[21 31 41 51]
[[21 31]
 [41 51]]
[[ 1  2  3  4 21 31]
 [ 5  6  7  8 41 51]]


---

Accessing elements of 2d arrays -> Time and Space Complexity = O(1)

In [43]:
arr2

array([[13, 22, 75, 36],
       [22, 74, 90, 10],
       [11, 19, 66, 71]])

In [44]:
arr2[1,2]

90

In [45]:
arr2[2,1]

19

In [46]:
arr2[2][1]

19

In [60]:
arr2[1:3,:]

array([[22, 74, 90, 10],
       [11, 19, 66, 71]])

In [63]:
# returning number of rows
len(arr2)

3

In [64]:
# returning number of columns
len(arr2[0])

4

In [72]:
# Create a funtion that will access any element of a given array

def access_array_element(input_array,row_index,column_index):
    if row_index >= len(input_array) or column_index >= len(input_array[0]):
        print("index out of bounds for the given array")
    else:
        return input_array[row_index,column_index]

In [74]:
access_array_element(arr2,3,2)

index out of bounds for the given array


---

Traversing a 2D array -> If rows=columns then the Time Complexity is O(n^2) otherwise the Time Complexity is O(m x n). Space Complexity is O(1)

In [75]:
arr2

array([[13, 22, 75, 36],
       [22, 74, 90, 10],
       [11, 19, 66, 71]])

In [77]:
for i in range(len(arr2)):
    for j in range(len(arr2[0])):
        print(arr2[i][j])

13
22
75
36
22
74
90
10
11
19
66
71


In [79]:
# create a function for it
def traverse_2d_array(input_array):
    for i in range(len(input_array)):
        for j in range(len(input_array[0])):
            print(arr2[i][j])

In [82]:
traverse_2d_array(arr2)

13
22
75
36
22
74
90
10
11
19
66
71


---

Searching for a value in a 2D array -> If rows=columns then the Time Complexity is O(n^2) otherwise the Time Complexity is O(m x n). Space Complexity is O(1)

In [83]:
arr2

array([[13, 22, 75, 36],
       [22, 74, 90, 10],
       [11, 19, 66, 71]])

In [86]:
def search_2d(input_array, value_to_search):
    traversed_list = []
    for i in range(len(input_array)):
        for j in range(len(input_array[0])):
            traversed_list.append(arr2[i][j])

    if value_to_search in traversed_list:
        return True
    else:
        return False
    

In [89]:
search_2d(arr2,91)

False

In [ ]:
# more efficient code: This is an example of linear search. There are other more efficient searching algorithms as well
def search_2d(input_array, value_to_search):
    for i in range(len(input_array)):
        for j in range(len(input_array[0])):
            if arr2[i][j] == value_to_search:
                return True
    return False

In [104]:
search_2d(arr2,90)

True

---

Deletion in 2D arrays -> Time and Space Complexity for Deletion is O(m x n)

In [110]:
print(arr2)
arr2_copy = np.delete(arr2,1,axis=0)
print()
print(arr2_copy)

[[13 22 75 36]
 [22 74 90 10]
 [11 19 66 71]]

[[13 22 75 36]
 [11 19 66 71]]
