In [31]:
from array import *

1.  Create an array and traverse it.

In [32]:
arr = array('i',[12,122,33,45,25,63,11,6,2,22])

In [33]:
for i in arr:
    print(i)

# Note: Space Complexity for creating arr is O(n) and Time Complexity for traversing arr is O(n) as well.

12
122
33
45
25
63
11
6
2
22


2. Access individual elements through indexes

In [34]:
arr[0]

12

In [35]:
arr[-1]

22

In [36]:
arr[3:6]

array('i', [45, 25, 63])

In [37]:
arr[::-1]

# Note: Time and Space complexity for accessing any individual element from an array is O(1)

array('i', [22, 2, 6, 11, 63, 25, 45, 33, 122, 12])

3. Append any value to the array using the append() method

In [38]:
arr.append(100)

# Note: Appending a value at the end of an array has a Time and Space complexity of O(1)

In [39]:
arr

array('i', [12, 122, 33, 45, 25, 63, 11, 6, 2, 22, 100])

4. Insert value in an array using the insert() method

In [40]:
arr.insert(9,200)

In [41]:
arr

# Note: Inserting anywhere within the array has a Time Complexity of O(n) and Space Complexity of O(1)

array('i', [12, 122, 33, 45, 25, 63, 11, 6, 2, 200, 22, 100])

5. Extend an array using the extend method

In [42]:
arr2 = array('i',[1,2,3,4,5])

In [43]:
arr.extend(arr2)

In [44]:
arr

# Note: Extending the array has a Time and Space Complexity of O(n)

array('i', [12, 122, 33, 45, 25, 63, 11, 6, 2, 200, 22, 100, 1, 2, 3, 4, 5])

6. Add items from list into array using fromlist() method

In [45]:
my_list=[20,30,40,50]

In [46]:
arr.fromlist(my_list)

In [47]:
arr

array('i', [12, 122, 33, 45, 25, 63, 11, 6, 2, 200, 22, 100, 1, 2, 3, 4, 5, 20, 30, 40, 50])

7. Remove any array element using remove() method

In [48]:
arr.remove(12)

In [49]:
arr
# Note: Removing an element from the array has a Time Complexity of O(n) and a Space Complexity of O(1)

array('i', [122, 33, 45, 25, 63, 11, 6, 2, 200, 22, 100, 1, 2, 3, 4, 5, 20, 30, 40, 50])

8. Remove the last element of an array using the pop() method

In [50]:
print(arr)
arr.pop()
print(arr)

array('i', [122, 33, 45, 25, 63, 11, 6, 2, 200, 22, 100, 1, 2, 3, 4, 5, 20, 30, 40, 50])
array('i', [122, 33, 45, 25, 63, 11, 6, 2, 200, 22, 100, 1, 2, 3, 4, 5, 20, 30, 40])


9. Fetch any element through it's index using the index() method

In [51]:
arr.index(33)

1

10. Reverse an array using the reverse() method

In [52]:
arr.reverse()
print(arr)

array('i', [40, 30, 20, 5, 4, 3, 2, 1, 100, 22, 200, 2, 6, 11, 63, 25, 45, 33, 122])


11. Get array buffer information through buffer_info() method

In [53]:
arr.buffer_info()

(2397868299056, 19)

12. Check for number of occurences of an element using count() method

In [54]:
arr.count(2)

2

13. Convert array to list using tolist() method

In [55]:
print(arr.tolist())
print(arr)

[40, 30, 20, 5, 4, 3, 2, 1, 100, 22, 200, 2, 6, 11, 63, 25, 45, 33, 122]
array('i', [40, 30, 20, 5, 4, 3, 2, 1, 100, 22, 200, 2, 6, 11, 63, 25, 45, 33, 122])


15. Slice elements from an array

In [56]:
arr[3:10]

array('i', [5, 4, 3, 2, 1, 100, 22])

---

2D Arrays

In [57]:
import numpy as np

In [58]:
arr2 = np.array([[13,22,75,36],[22,74,90,10],[11,19,66,71]])

# Note: The time and space complexity for creating a 2d-array is O(mXn) where m = no. of rows and n=no. of columns

In [59]:
arr2

array([[13, 22, 75, 36],
       [22, 74, 90, 10],
       [11, 19, 66, 71]])

---

Insertion in 2d arrays:
1. Adding columns: Each column moves 1 step forward (time consuming - O(m X n))
2. Adding rows =: Each row moves 1 step down (time consuming - O(m X n))

In [112]:
arr2

array([[13, 22, 75, 36],
       [22, 74, 90, 10],
       [11, 19, 66, 71]])

In [113]:
# using the insert() method to add a column
np.insert(arr2,0,[[0,0,0]],axis=1)

array([[ 0, 13, 22, 75, 36],
       [ 0, 22, 74, 90, 10],
       [ 0, 11, 19, 66, 71]])

In [116]:
# using the insert() method to add a row
np.insert(arr2,0,[[0,0,0,0]],axis=0)

array([[ 0,  0,  0,  0],
       [13, 22, 75, 36],
       [22, 74, 90, 10],
       [11, 19, 66, 71]])

In [125]:
# using the append method to add row
np.append(arr2,[[0,0,0,0]],axis=0)

array([[13, 22, 75, 36],
       [22, 74, 90, 10],
       [11, 19, 66, 71],
       [ 0,  0,  0,  0]])

In [120]:
# using the append method to add column
np.append(arr2,[[0],[0],[0]],axis=1)

array([[13, 22, 75, 36,  0],
       [22, 74, 90, 10,  0],
       [11, 19, 66, 71,  0]])

In [126]:
# make numpy automatically detect dimentions and append a given row
arr_to_append = np.array([[0,0,0]])

In [127]:
arr_to_append = arr_to_append.reshape(arr2.shape[0], -1)

In [128]:
np.append(arr2,arr_to_append,axis=1)

array([[13, 22, 75, 36,  0],
       [22, 74, 90, 10,  0],
       [11, 19, 66, 71,  0]])

In [110]:
# Assuming this is your twoDArray
twoDArray = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(twoDArray)
# The new array to append
new_array = np.array([21, 31, 41, 51])
print(new_array)
# Reshape new_array to have the same number of rows as twoDArray and 1 column
new_array = new_array.reshape(twoDArray.shape[0], -1)
print(new_array)
# Append new_array to twoDArray
new_append = np.append(twoDArray, new_array, axis=1)
print(new_append)

[[1 2 3 4]
 [5 6 7 8]]
[21 31 41 51]
[[21 31]
 [41 51]]
[[ 1  2  3  4 21 31]
 [ 5  6  7  8 41 51]]
